stages:
  - test

variables:
  APPID: Flames
  VERSION: 1.0.0
  LASTVERSION: 1.0.0
  PROJECTDIR: D:\wwl\abuwms\
  GRADLE_USER_HOME: C:\Users\wwl\.gradle

test:
  stage: test
  script:
    - echo $pwd
    - $date = $(Get-Date -Format 'yyyyMMdd')
    - echo $date
    - $content=get-content "vue.config.js" -encoding utf8
    # powershell ref: https://learn.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.2#matching-operators
    - if ($content -match "process.env.VUE_APP_VERSION = [`"|'](.*?)[`"|']") {    $Matches   }
    - if ($Matches.Count -gt 1) {$VERSION = $Matches[1]}
    # - $content = $content -replace "process.env.VUE_APP_VERSION = [`"|'](.*?)[`"|']","process.env.VUE_APP_VERSION = `"$VERSION`""
    # - $content = $content -replace "Flames-M","$APPID-$CI_COMMIT_REF_NAME"
    # - $content = $content -replace "builds",$CI_PIPELINE_ID
    - $content = $content -replace "versionDate",$date
    - $content | out-file "vue.config.js" -encoding utf8
  tags:
    - tobeshell
  only:
    - master